HNStationaryStore/Models/EF/ProductCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HNStationaryStore.Models.EF
{
    public class ProductCategory
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CategoryId { get; set; }
        [Required(ErrorMessage = ("Tên danh mục không được để trống"))]
        [StringLength(100)]
        public string CategoryName { get; set; }

        public virtual ICollection<SubCategory> SubCategories { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}

HNStationaryStore/Areas/Admin/Controllers/ProductCategoryController.cs
using HNStationaryStore.Models;
using HNStationaryStore.Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HNStationaryStore.Areas.Admin.Controllers
{
    [Authorize(Roles = ("admin, employee"))]
    public class ProductCategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/ProductCategory
        public ActionResult Index()
        {
            var items = db.ProductCategories.ToList();
            return View(items);
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ProductCategory model)
        {
            if (ModelState.IsValid)
            {
                
                db.ProductCategories.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Edit(int id)
        {
            var ProductCate = db.ProductCategories.Find(id);
            if (ProductCate == null)
            {
                return HttpNotFound();
            }
            return View(ProductCate);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductCategory model)
        {
            if (ModelState.IsValid)
            {
                var existingCategory = db.ProductCategories.Find(model.CategoryId);
                if (existingCategory == null)
                {
                    return HttpNotFound();
                }
                existingCategory.CategoryName = model.CategoryName;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Delete(int id)
        {
            var item = db.ProductCategories.Find(id);
            if (item != null)
            {
                db.ProductCategories.Remove(item);
                db.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
       


    }
}

HNStationaryStore/Areas/Admin/Views/ProductCategory/Add.cshtml
@model HNStationaryStore.Models.EF.ProductCategory
@{
    ViewBag.Title = "Thêm mới Danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="row mb-2">
    <div class="col-sm-6">
        <h3 class="fw-bold text-dark">Thêm mới danh mục san phẩm</h3>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/admin/home">Home</a></li>
            <li class="breadcrumb-item"><a href="/admin/ProductCategory">Danh mục</a></li>
            <li class="breadcrumb-item active">Thêm mới</li>
        </ol>
    </div>
</div>

<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5 class="card-title fw-bold text-dark mb-0">Thông tin thêm mới danh mục</h5>

        </div>
        <div class="card-body">
            <div class="card-body p-0">
                <div class="bs-stepper-content">
                    @using (Html.BeginForm("Add", "ProductCategory", FormMethod.Post, new { }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(false)
                        <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
                            <div class="form-group">
                                <label for="exampleInputEmail1" style="color: #222; font-weight: 700;">Tên danh muc</label>
                                @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control", @placeholder = "Tên danh mục" })
                                @Html.ValidationMessageFor(x => x.CategoryName, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div id="information-part" class="content" role="tabpanel" aria-labelledby="information-part-trigger">

                            <a href="/admin/ProductCategory" class="btn btn-danger">Quay lại</a>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    }

                </div>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>

HNStationaryStore/Areas/Admin/Views/ProductCategory/Edit.cshtml
@model HNStationaryStore.Models.EF.ProductCategory

@{
    ViewBag.Title = "Cập nhật danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row mb-2">
    <div class="col-sm-6">
        <h3 class="fw-bold text-dark">Cập nhật danh mục</h3>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/admin/home">Home</a></li>
            <li class="breadcrumb-item"><a href="/admin/ProductCategory">Danh mục sản phẩm</a></li>
            <li class="breadcrumb-item active">Cập nhật</li>
        </ol>
    </div>
</div>

<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5 class="card-title fw-bold text-dark mb-0">Thông tin danh mục sản phẩm</h5>

        </div>
        <div class="card-body">
            <div class="card-body p-0">
                <div class="bs-stepper-content">
                    @using (Html.BeginForm("Edit", "ProductCategory", FormMethod.Post, new { }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(false)
                        @Html.HiddenFor(x => x.CategoryId)
                        <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
                            <div class="form-group">
                                <label for="exampleInputEmail1" style="color: #222; font-weight: 700;">Tên danh muc</label>
                                @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control", @placeholder = "Tên danh mục" })
                                @Html.ValidationMessageFor(x => x.CategoryName, null, new { @class = "text-danger" })
                            </div>
                            

                        </div>
                        <div id="information-part" class="content" role="tabpanel" aria-labelledby="information-part-trigger">

                            <a href="/admin/ProductCategory" class="btn btn-danger">Quay lại</a>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    }

                </div>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>

HNStationaryStore/Areas/Admin/Views/ProductCategory/Index.cshtml
@model IEnumerable<HNStationaryStore.Models.EF.ProductCategory>
@{
    ViewBag.Title = "Danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
            <h3 style="color: #222; font-weight: 700;">Quản lý danh mục sản phẩm</h3>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/admin/home">Home</a></li>
                <li class="breadcrumb-item active">Danh mục sản phẩm</li>
            </ol>
        </div>
    </div>

    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="card-title mb-0" style="color: #222; font-weight: 700;">Danh mục</h5>
                <div class="card-tools">
                    <a href="/admin/ProductCategory/add" class="btn btn-primary">Thêm mới</a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên danh mục sản phẩm</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Any())
                        {
                            var i = 1;
                            foreach (var item in Model)
                            {
                                <tr id="trow_@item.CategoryId">
                                    <td>@i</td>
                                    <td>@item.CategoryName</td>
                                    <td>
                                        <a href="/admin/productCategory/edit/@item.CategoryId" class="btn btn-sm btn-primary">Sửa</a>
                                        <a href="#" data-id="@item.CategoryId" class="btn btn-sm btn-danger btnDelete">Xóa</a>
                                    </td>
                                </tr>
                                i++;
                            }

                        }
                        else
                        {
                            <tr>
                                <td colspan="4" class="text-center">Không có bản ghi nào</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">

            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

    </section>
</div><!-- /.container-fluid -->
@section scripts{
    <script>
        $(document).ready(function () {
            $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id");
                var conf = confirm("Bạn có muốn xóa bản ghi này không ?");
                if (conf === true) {
                    $.ajax({
                        url: '/admin/ProductCategory/delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();
                            }
                        }
                    });
                }
            });
        });
    </script>
}